# Generated by Django 4.0.6 on 2024-01-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0007_tbldeliveryhistory_tbldelivery_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldeliveryhistory',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tbldeliveryhistory',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tbldeliveryhistory',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
