# Generated by Django 4.0.6 on 2025-03-04 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblcrjournalentry',
            name='paidfrom_ledger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries_paidfrom', to='accounting.accountledger'),
        ),
        migrations.AddField(
            model_name='tbldrjournalentry',
            name='paidfrom_ledger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debit_entries_paidfrom', to='accounting.accountledger'),
        ),
    ]
